### ISSUE TITLE
non-static const is causing problems

### ISSUE THREAD

**Issue by stewpend0us** [eminfedar/async-sockets-cpp#27]
in basesocket.hpp line 29:
`const uint16_t BUFFER_SIZE = 0xFFFF;`

please make it:
`static const uint16_t BUFFER_SIZE = 0xFFFF;`

otherwise the function 'TCPSocket& TCPSocket::operator=(TCPSocket&&)' is deleted by the compiler and I can't do
`mysocket = TCPSocket();`

just changing that one constant to be static fixes the problem for me and works great

**Comment by eminfedar** [comment]
I updated the code. Can you try it again by pulling master branch again?

I think it is fixed.

[fb72473](https://github.com/eminfedar/async-sockets-cpp/commit/fb72473e7f5ec38006107d924c248a17370ca7bd)

**Comment by stewpend0us** [comment]
That does fix the original issue but I still have the same problem now because of the new atomic bool member:
`/usr/local/include/async-sockets/tcpsocket.hpp:9:7: error: use of deleted function ‘BaseSocket& BaseSocket::operator=(BaseSocket&&)’`
`/usr/local/include/async-sockets/basesocket.hpp:21:7: error: use of deleted function ‘std::atomic<bool>& std::atomic<bool>::operator=(const std::atomic<bool>&)’`

changing it back to regular bool fixes it....but not the race issue. Not sure how to solve that.

This seems to suggest that tracking the state of the socket (isClosed) maybe isn't necessary?
https://stackoverflow.com/a/12411808/3381816

They seem to say to just assume that the socket is good to go and handle the errors as they come up (which you do already).

Maybe you could just eliminate the isClosed variable and everything would still work?

**Comment by stewpend0us** [comment]
Also changing the "Connect" methods to take char * instead of string broke my code (trivial and I don't really care...but some may be annoyed)

Maybe use a `const std::string_view IP` that supports both string and char * as input https://softwareengineering.stackexchange.com/a/364094

**Comment by eminfedar** [comment]
> Maybe use a `const std::string_view IP` that supports both string and char * as input

We can but `string_view` is supported in C++17: https://en.cppreference.com/w/cpp/header/string_view

This library uses C++11, we can update it to C++17 too, or I can overload the method with both `const char*` and `const std::string&` reference parameters.

> This seems to suggest that tracking the state of the socket (isClosed) maybe isn't necessary?

This is actually right. I will test it and maybe I can remove it. 👍🏻

**Comment by eminfedar** [comment]
Removed isClosed, please check in your case :) @stewpend0us

**Comment by stewpend0us** [comment]
Looks good so far! Last nit: udpSocket doesn't have a Connect(string,...) version

removing isClosed actually simplified my own logic too which is nice. hopefully it works out that way for others too

**Comment by eminfedar** [comment]
Updated again. Your feedback is welcome! :) @stewpend0us

**Comment by stewpend0us** [comment]
Just realized you reduced BUFFER_SIZE from 0xFFFF to 0x1000. Wondering why. Any way this could be a configurable value? Or maybe just have another signature for Receive where you can pass your own buffer in?

**Comment by eminfedar** [comment]
Related to #29 and fixed in #28
